#!/usr/bin/env python3

import subprocess
from colorama import Fore, Back, Style
import time



def main():
    # ---------------------------------------------------
    # INITIALIZATION
    # ---------------------------------------------------

    arena_selected = False
    mode_selected = False
    custom_mode = False
    red_defined = False
    blue_defined = False
    green_defined = False
    custom_defined = False

    # ---------------------------------------------------
    # SELECT ARENA
    # ---------------------------------------------------

    arena = input(Style.BRIGHT + Back.LIGHTYELLOW_EX + Fore.BLACK + '\nWELCOME TO THE TEAM HUNT GAME\n\n' + Style.RESET_ALL + Style.BRIGHT + 'CHOOSE THE ARENA: 1,2 or 3?\n'+ Style.RESET_ALL )

    while arena_selected == False:

        if arena == '1' or arena == '2' or arena == '3':
            arena_selected = True
            print(Fore.YELLOW + Style.BRIGHT + ' \nYOU SELECTED THE ARENA ' + arena + Style.RESET_ALL)
        else:
            arena_selected = False
            arena = input(Fore.LIGHTYELLOW_EX + Style.BRIGHT + 'Arena name not valid! Type 1,2 or 3.\n' + Style.RESET_ALL)

    # ---------------------------------------------------
    # SELECT MODE
    # ---------------------------------------------------

    mode = input('\n\nUse which mode? [n, t, c]\n\n'
                 'n - Normal Mode (3R x 3G x 3B)\n'
                 't - Test Mode (3R x 1G x 1B)\n'
                 'c - Custom mode (Choose number per team)\n\n')

    while mode_selected == False:

        if mode == 'n':
            mode_selected = True
            custom_mode = False
            print(Fore.LIGHTBLUE_EX + '\nSelected Normal Mode (3 x 3 x 3)\n' + Style.RESET_ALL)
        elif mode == 't':
            mode_selected = True
            custom_mode = False
            print(Fore.LIGHTBLUE_EX + '\nSelected Test Mode (3 x 1 x 1)\n' + Style.RESET_ALL)
        elif mode == 'c':
            mode_selected = True
            custom_mode = True
            print(Fore.LIGHTBLUE_EX + '\nSelected custom mode. Define how many per team!\n' + Style.RESET_ALL)
        else:
            mode_selected = False
            custom_mode = False
            mode = input(Fore.LIGHTYELLOW_EX + '\nMode does not exist! Type n,t or c.\n'
                         'n - Normal Mode (3R x 3G x 3B)\n'
                         't - Test Mode (3R x 1G x 1B)\n'
                         'c - Custom mode (Choose number per team)\n' + Style.RESET_ALL)

    # ---------------------------------------------------
    # CUSTOM MODE PARAMETERS
    # ---------------------------------------------------

    if custom_mode == True:

        while custom_defined == False:

            # ---------------------------------------------------
            # CUSTOM MODE PARAMETERS: RED
            # ---------------------------------------------------

            red_number = input(Style.BRIGHT + 'How many' + Fore.RED + ' Red ' + Fore.RESET + 'players? 1,2 or 3?\n' + Style.RESET_ALL)

            while red_defined == False:

                if red_number == '1' or red_number == '2' or red_number == '3':
                    red_defined = True
                    print('\n\nNumber of players:\n'
                          + Fore.RED + 'Red: ' + Style.RESET_ALL + red_number + '\n' )

                else:
                    red_defined = False
                    red_number = input(Fore.LIGHTYELLOW_EX + Style.BRIGHT + 'Number not valid! Type 1,2 or 3.\n' + Style.RESET_ALL)

            # ---------------------------------------------------
            # CUSTOM MODE PARAMETERS: GREEN
            # ---------------------------------------------------

            green_number = input(Style.BRIGHT + 'How many' + Fore.GREEN + ' Green ' + Fore.RESET + 'players? 1,2 or 3?\n' + Style.RESET_ALL)

            while green_defined == False:

                if green_number == '1' or green_number == '2' or green_number == '3':
                    green_defined = True
                    print('\n\nNumber of players:\n'
                          + Fore.RED + 'Red: ' + Style.RESET_ALL + red_number + '\n'
                          + Fore.GREEN + 'Green: ' + Style.RESET_ALL + green_number + '\n')

                else:
                    green_defined = False
                    green_number = input(Fore.LIGHTYELLOW_EX + Style.BRIGHT + 'Number not valid! Type 1,2 or 3.\n' + Style.RESET_ALL)

            # ---------------------------------------------------
            # CUSTOM MODE PARAMETERS: BLUE
            # ---------------------------------------------------

            blue_number = input(Style.BRIGHT + 'How many' + Fore.BLUE + ' Blue ' + Fore.RESET + 'players? 1,2 or 3?\n' + Style.RESET_ALL)

            while blue_defined == False:

                if blue_number == '1' or blue_number == '2' or blue_number == '3':
                    blue_defined = True
                    print('\n\nNumber of players:\n'
                          + Fore.RED + 'Red: ' + Style.RESET_ALL + red_number + '\n'
                          + Fore.GREEN + 'Green: ' + Style.RESET_ALL + green_number + '\n'
                          + Fore.BLUE + 'Blue: ' + Style.RESET_ALL + blue_number + '\n')

                else:
                    blue_defined = False
                    blue_number = input(Fore.LIGHTYELLOW_EX + Style.BRIGHT + 'Number not valid! Type 1,2 or 3.\n' + Style.RESET_ALL)

            if red_defined == True and green_defined == True and blue_defined == True:
                if red_number == blue_number == green_number == '3':
                    mode = 'n'
                elif red_number == '3' and (blue_number == green_number == '1'):
                    mode = 't'
                else:
                    mode = 'c'
                print(Fore.LIGHTBLUE_EX + Style.BRIGHT + 'Custom Mode defined.\n' + Style.RESET_ALL)
                custom_defined = True
                continue

    # ---------------------------------------------------
    # LAUNCH GAME
    # ---------------------------------------------------

    start = input('Everything is set. START GAME? [Y/n]\n')

    if start == 'y' or start == 'Y':

        if mode == 'n' or mode == 't':

            string_to_launch = 'roslaunch p_g06_menu game_start_' + str(mode) + '.launch arena:=' + str(arena)

        else:

            string_to_launch = 'roslaunch p_g06_menu game_start_c.launch arena:=' + str(arena) + ' rnumber:=' + red_number + ' gnumber:=' + green_number + ' bnumber:=' + blue_number

        subprocess.run(string_to_launch, shell=True)
        # print(string_to_launch)
if __name__ == '__main__':
    main()
