#!/usr/bin/env python3

import os

def main():
    # ---------------------------------------------------
    # INITIALIZATION
    # ---------------------------------------------------

    os.system("rosrun th_referee th_referee")




if __name__ == '__main__':
    main()
